# Generated by Django 4.0.6 on 2022-08-28 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the user was created', verbose_name='Joined on')),
                ('email', models.EmailField(help_text="User's email address (optional)", max_length=255, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user should be treated as active', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether this user has access to the admin site', verbose_name='Staff')),
                ('name', models.CharField(help_text="User's full name", max_length=255, verbose_name='Name')),
                ('username', models.CharField(help_text='Username (must be unique)', max_length=255, unique=True, verbose_name='Username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
